services:
 nifi:
   image: apache/nifi:1.21.0
   container_name: nifi
   user: "root"
   ports:
     - "8080:8080"
   networks:
     - confluent
   environment:
     NIFI_WEB_HTTP_PORT: 8080
   volumes:
     - ./nifi_data:/opt/nifi/nifi-current/data
     - ./nifi_config:/opt/nifi/nifi-current/config
volumes:
 nifi_data:
 nifi_config:
networks:
 confluent: